/*CREATE DATABASE dog_db;*/

/*\c dog_db;*/

CREATE TABLE userTable (
	uid VARCHAR(256) PRIMARY KEY, 
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE imageTable (
	img VARCHAR(256) PRIMARY KEY, 
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	breed VARCHAR(32)
);

CREATE TABLE uidTable (
	pid VARCHAR(256) PRIMARY KEY, 
	uid VARCHAR(256) REFERENCES userTable(uid),
	expires TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE evlTable (
	uid VARCHAR(256) REFERENCES userTable(uid),
	img VARCHAR(256) REFERENCES imageTable(img),
	date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	evl INT DEFAULT 0,
	fav INT DEFAULT 0,
	PRIMARY KEY(uid, img)
);

CREATE TABLE commentTable (
	uid VARCHAR(256) REFERENCES userTable(uid),
	img VARCHAR(256) REFERENCES imageTable(img),
	date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	comment VARCHAR(16384)
);
